=== raml-apis/Office365/schemas/calendarRepresentation-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "@odata.id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "@odata.editLink" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "ChangeKey" : {
      "type" : "string" ,
      "required" : false
    } ,
    "ClassId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Calendars@odata.navigationLink" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Office365/examples/calendarRepresentation-example.json
{
  "@odata.id" : "https://outlook.office365.com/EWS/OData/Users('sadie@contoso.com')/CalendarGroups('AQMkAGI3...')" ,
  "@odata.editLink" : "https://outlook.office365.com/EWS/OData/Users('sadie@contoso.com')/CalendarGroups('AQMkAGI3...')" ,
  "Id" : "AQMkAGI3..." ,
  "Name" : "My Calendars" ,
  "ChangeKey" : "R9CVg8njOEeBFPLI1qvQugAAAAAI5A==" ,
  "ClassId" : "0006f0b7-0000-0000-c000-000000000046" ,
  "Calendars@odata.navigationLink" : "https://outlook.office365.com/EWS/OData/Users('sadie@contoso.com')/CalendarGroups('AQMkAGI3...')/Calendars"
}
