=== raml-apis/Office365/schemas/contacts-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "@odata.id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "@odata.editLink" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "ParentFolderId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "DisplayName" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Contacts@odata.navigationLink" : {
      "type" : "string" ,
      "required" : false
    } ,
    "ChildFolders@odata.navigationLink" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Office365/examples/contacts-example.json
{
  "@odata.id": "https://outlook.office365.com/EWS/OData/Users('sadie@contoso.com')/ContactFolders('AAMkADA5...')",
  "@odata.editLink": "https://outlook.office365.com/EWS/OData/Users('sadie@contoso.com')/ContactFolders('AAMkADA5...')",
  "Id": "AAMkADA5...",
  "ParentFolderId": "AAMkADA5...",
  "DisplayName": "Contacts",
  "Contacts@odata.navigationLink": "https://outlook.office365.com/EWS/OData/Users('sadie@contoso.com')/ContactFolders('AAMkADA5...')/Contacts",
  "ChildFolders@odata.navigationLink": "https://outlook.office365.com/EWS/OData/Users('sadie@contoso.com')/ContactFolders('AAMkADA5...')/ChildFolders"
}
