=== raml-apis/Office365/schemas/getFolderById-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "@odata.id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "@odata.editLink" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "ParentFolderId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "DisplayName" : {
      "type" : "string" ,
      "required" : false
    } ,
    "ClassName" : {
      "type" : "string" ,
      "required" : false
    } ,
    "TotalCount" : {
      "type" : "number" ,
      "required" : false
    } ,
    "ChildFolderCount" : {
      "type" : "number" ,
      "required" : false
    } ,
    "UnreadItemCount" : {
      "type" : "number" ,
      "required" : false
    } ,
    "ChildFolders@odata.navigationLink" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Messages@odata.navigationLink" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Office365/examples/getFolderById-example.json
{
  "@odata.id": "https://outlook.office365.com/EWS/OData/Users('sadie@contoso.com')/Folders('AAMkAGI3...')",
  "@odata.editLink": "https://outlook.office365.com/EWS/OData/Users('sadie@contoso.com')/Folders('AAMkAGI3...')",
  "Id": "AAMkAGI3...",
  "ParentFolderId": "AQMkAGI3...",
  "DisplayName": "Inbox",
  "ClassName": "IPF.Note",
  "TotalCount": 0,
  "ChildFolderCount": 0,
  "UnreadItemCount": 0,
  "ChildFolders@odata.navigationLink": "https://outlook.office365.com/EWS/OData/Users('sadie@contoso.com')/Folders('AAMkAGI3...')/ChildFolders",
  "Messages@odata.navigationLink": "https://outlook.office365.com/EWS/OData/Users('sadie@contoso.com')/Folders('AAMkAGI3...')/Messages"
}
