=== raml-apis/Office365/schemas/newEvent-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "@odata.type" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Subject" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Body" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "ContentType" : {
          "type" : "string" ,
          "required" : false
        } ,
        "Content" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "Start" : {
      "type" : "string" ,
      "required" : false
    } ,
    "End" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Location" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "DisplayName" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "ShowAs" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Attendees" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "Name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "Address" : {
              "type" : "string" ,
              "required" : false
            } ,
            "Type" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    }
  }
}

=== raml-apis/Office365/examples/newEvent-example.json
{
  "@odata.type": "#Microsoft.Exchange.Services.OData.Model.Event",
  "Subject": "Discuss the Calendar REST API",
  "Body": {
    "ContentType": "HTML",
    "Content": "I think it will meet our requirements!"
  },
  "Start": "2014-07-02T18:00:00Z",
  "End": "2014-07-02T19:00:00Z",
  "Location": {
      "DisplayName": "Conference Room 1"
    },
  "ShowAs": "Busy",
  "Attendees": [
    {
      "Name": "Alex Darrow",
      "Address": "alexd@contoso.com",
      "Type": "Required"
    },
    {
      "Name": "Anne Wallace",
      "Address": "annew@contoso.com",
      "Type": "Optional"
    },
    {
      "Name": "Conference Room 1",
      "Address": "conf1@contoso.com",
      "Type": "Resource"
    }
  ]
}
